### ISSUE TITLE
Webpack 4 compatibility

### ISSUE THREAD

**Issue by Saravanan90** [tomachristian/css-entry-webpack-plugin#26]
Getting this error when used with webpack 4

```
/app/node_modules/webpack/lib/Compilation.js:1837
  ].call(...args);
    ^

TypeError: Cannot read property 'call' of undefined
    at Compilation.<anonymous> (/app/node_modules/webpack/lib/Compilation.js:1837:4)
    at Compilation.deprecated [as applyPlugins] (internal/util.js:47:15)
    at compiler.plugin (/app/node_modules/css-entry-webpack-plugin/lib/CssEntryPlugin.js:52:68)
    at SyncHook.eval [as call] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:13:1)
    at SyncHook.lazyCompileHook [as _call] (/app/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (/app/node_modules/webpack/lib/Compiler.js:417:30)
    at hooks.beforeCompile.callAsync.err (/app/node_modules/webpack/lib/Compiler.js:457:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (/app/node_modules/webpack/lib/Compiler.js:452:28)
    at readRecords.err (/app/node_modules/webpack/lib/Compiler.js:200:11)
    at Compiler.readRecords (/app/node_modules/webpack/lib/Compiler.js:322:11)
    at hooks.run.callAsync.err (/app/node_modules/webpack/lib/Compiler.js:197:10)
    at _err0 (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at compiler.hooks.run.tapAsync (/app/node_modules/webpack/lib/CachePlugin.js:46:60)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.beforeRun.callAsync.err (/app/node_modules/webpack/lib/Compiler.js:194:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/app/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/app/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.run (/app/node_modules/webpack/lib/Compiler.js:191:24)
    at processOptions (/app/node_modules/webpack-cli/bin/webpack.js:499:20)
    at yargs.parse (/app/node_modules/webpack-cli/bin/webpack.js:502:3)
    at Object.parse (/app/node_modules/webpack-cli/node_modules/yargs/yargs.js:539:18)
    at /app/node_modules/webpack-cli/bin/webpack.js:212:8
    at Object.<anonymous> (/app/node_modules/webpack-cli/bin/webpack.js:504:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/webpack/bin/webpack.js:12:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
```

**Comment by bennadel** [comment]
Ok, not just me then :)

**Comment by Sloth9527** [comment]
+1 !

**Comment by artemsky** [comment]
++

**Comment by sharifzadesina** [comment]
+

**Comment by tomachristian** [comment]
With the advent of native CSS modules support in Webpack (https://github.com/webpack/webpack/pull/6448) and due to lack of time on my part in maintaining this plugin, the project has been discontinued. If anyone wants to continue work on this, PRs are welcome 💯

**Comment by afeiship** [comment]
+1

**Comment by Lenic** [comment]
+1
